image:
- Visual Studio 2019
#- macOS
#- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: YKiulnh6g4lVHcmMHwR4Hs8i53ID022Cb9KpBMRxMAAEKf8fFfbzOtK7N7SRCT7A

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name XLink --onedir --icon icon.ico --product-name XLink --add-data "asset;asset" --product-version "0.1.0" --copyright "Copyright (c) 2023 XCorporations Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  release: XLink
  description: 'Release description'
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a XLink.zip %CD%\dist\*

  artifacts:
  - path: XLink.zip

#
#   macOS package
# 
#-
#  matrix:
#    only:
#    - image: macOS

#  after_build:
#  - tar -czvf counter-macos.tar.gz -C dist counter.app

#  artifacts:
#  - path: counter-macos.tar.gz

#
#   Linux package
# 
#-
#  matrix:
#    only:
#    - image: Ubuntu

#  after_build:
#  - tar -czvf counter-linux.tar.gz -C dist counter

#  artifacts:
#  - path: counter-linux.tar.gz
