name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6
    - name: Clone Repo
      run: |
        git clone https://github.com/username/XLink-pc.git
        cd XLink-pc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with Flet
      run: |
        flet pack main.py --name XLink --onedir --icon icon.ico --product-name XLink --product-version "1.0.0" --copyright "Copyright (c) 2024 XCorporations Inc."
    - name: Compress folder
      shell: powershell
      run: |
        Compress-Archive -Path dist/XLink -DestinationPath XLink.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_XLINK }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          This is the first release.
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_XLINK }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./XLink.zip
        asset_name: XLink.zip
        asset_content_type: application/zip
